import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <React.StrictMode>
          <CartProvider>
            {children}
          </CartProvider>
        </React.StrictMode>
      </body>
    </html>
  );
}
